import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"
import { BlogProvider } from "./context/BlogContext"
import { UserProvider } from "./context/AuthContext"

import { Metadata } from "next/types"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<BlogProvider>
					<UserProvider>
						<div className='pb-16'>
							<Navbar />
						</div>
						{children}
					</UserProvider>
					<Footer />
				</BlogProvider>
			</body>
		</html>
	)
}
